app:
  name: "Go Next App"
  port: 8080
  debug: true
  workspace: /Users/Chaly/Downloads/YuGone/

captcha:
  expired: 10m

email:
  port: 587
  host: smtp.qq.com
  from: Any Support <admin@te0.cn>
  username:
  password:

mobile:
  sign_name:
  template_code:
  access_key_id:
  access_key_secret:

cache:
  dialect: redis
  host: 127.0.0.1
  port: 6379
  password: redis123

database:
  dialect: postgres
  host: 127.0.0.1
  port: 5678
  name: gcms
  username: postgres
  password: postgres

oss:
  #  vendor: 七牛
  #  region: z0
  #  bucket: eunut-tmp
  #  domain: http://qn.te0.cn
  #  access_key: rDpoieuu5Jyl-i915MuVyNVT0dFQJPHBFGEG4TlK
  #  secret_key: 6eVPc6EXTjaLVudIUQEU-QQviiA6r5YPbauVmAVY
  vendor: 阿里
  region: oss-cn-beijing.aliyuncs.com
  bucket: eunut-img
  domain: http://al.te0.cn
  access_key: LTAI5tFnu8tZg1kt358Y5diM
  secret_key: zw1QRLSGq6qGIIM1wuNju5kvN0uBxb