app:
  name: "Go Next App"
  port: 8080
  debug: true
  workspace: /Users/Chaly/Downloads/YuGone/

captcha:
  expired: 10m

email:
  port: 587
  host: smtp.qq.com
  from: Any Support <admin@te0.cn>
  username:
  password:

mobile:
  sign_name:
  template_code:
  access_key_id:
  access_key_secret:

cache:
  dialect: redis
  host: 127.0.0.1
  port: 6379
  password: redis123

database:
  dialect: postgres
  host: 127.0.0.1
  port: 5678
  name: gcms
  username: postgres
  password: postgres