app:
  name: "Go Next App"
  port: 8080
  debug: true
  workspace: /Users/Chaly/Downloads/YuGone/

captcha:
  expired: 10m

email:
  host: smtp.qq.com
  port: 587
  from: Any Support <admin@te0.cn>
  username: admin@te0.cn
  password: opzasepuoqzebhdf

cache:
  dialect: redis
  host: 127.0.0.1
  port: 6379
  password: redis123

database:
  dialect: postgres
  host: 127.0.0.1
  port: 5678
  name: gcms
  username: postgres
  password: postgres