"""
A cursor is an encoded string use for pagination
"""
scalar Cursor
"""
The `DateTime` scalar type represents a DateTime. The DateTime is serialized as an RFC 3339 quoted string
"""
scalar DateTime

"The direction of result ordering."
enum SortDirection {
    "Ascending order"
    ASC
    "Descending order"
    DESC
    "Ascending nulls first order"
    ASC_NULLS_FIRST
    "Descending nulls first order"
    DESC_NULLS_FIRST
    "Ascending nulls last order"
    ASC_NULLS_LAST
    "Descending nulls last order"
    DESC_NULLS_LAST
}

type Area {
    id: ID
    teamList: [Team]
}
input AreaSortInput {
    id: SortDirection
    teamList: SortDirection
}
type Edge {
    userId: ID
    teamId: ID
    user: User
    team: Team
}
input EdgeSortInput {
    userId: SortDirection
    teamId: SortDirection
    user: SortDirection
    team: SortDirection
}
type Item {
    id: ID
    userId: Int
    user: User
}
input ItemSortInput {
    id: SortDirection
    userId: SortDirection
    user: SortDirection
}
type Query {
    userList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:UserSortInput): [User]
    areaList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:AreaSortInput): [Area]
    teamList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:TeamSortInput): [Team]
    edgeList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:EdgeSortInput): [Edge]
    itemList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:ItemSortInput): [Item]
}
type Team {
    id: ID
    pid: Int
    areaId: Int
    edgeList: [Edge]
    userList: [User]
    parent: Team
    children: [Team]
    area: Area
}
input TeamSortInput {
    id: SortDirection
    pid: SortDirection
    areaId: SortDirection
    edgeList: SortDirection
    userList: SortDirection
    parent: SortDirection
    children: SortDirection
    area: SortDirection
}
type User {
    id: ID
    edgeList: [Edge]
    teamList: [Team]
    itemList: [Item]
}
input UserSortInput {
    id: SortDirection
    edgeList: SortDirection
    teamList: SortDirection
    itemList: SortDirection
}