"""
A cursor is an encoded string use for pagination
"""
scalar Cursor
"""
The `DateTime` scalar type represents a DateTime. The DateTime is serialized as an RFC 3339 quoted string
"""
scalar DateTime

"The direction of result ordering."
enum SortDirection {
    "Ascending order"
    ASC
    "Descending order"
    DESC
    "Ascending nulls first order"
    ASC_NULLS_FIRST
    "Descending nulls first order"
    DESC_NULLS_FIRST
    "Ascending nulls last order"
    ASC_NULLS_LAST
    "Descending nulls last order"
    DESC_NULLS_LAST
}

type Area {
    id: ID
    userList(distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:UserSortInput,where:UserWhereInput): [User]
}
input AreaSortInput {
    id: SortDirection
}
input AreaWhereInput {
    and: AreaWhereInput
    not: AreaWhereInput
    or: AreaWhereInput
    id: IDExpression
}
input BooleanExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Equals value
    """
    eq: Boolean
    """
    Does not equal value
    """
    ne: Boolean
    """
    Is greater than value
    """
    gt: Boolean
    """
    Is lesser than value
    """
    lt: Boolean
    """
    Is greater than or equals value
    """
    ge: Boolean
    """
    Is lesser than or equals value
    """
    le: Boolean
    """
    Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
    """
    like: Boolean
    """
    Value not matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
    """
    notLike: Boolean
}
input BooleanListExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Is in list of values
    """
    in: Boolean
    """
    Is not in list of values
    """
    notIn: Boolean
}
input FloatExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Equals value
    """
    eq: Float
    """
    Does not equal value
    """
    ne: Float
    """
    Is greater than value
    """
    gt: Float
    """
    Is lesser than value
    """
    lt: Float
    """
    Is greater than or equals value
    """
    ge: Float
    """
    Is lesser than or equals value
    """
    le: Float
    """
    Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
    """
    like: Float
    """
    Value not matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
    """
    notLike: Float
}
input FloatListExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Is in list of values
    """
    in: Float
    """
    Is not in list of values
    """
    notIn: Float
}
input IDExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Equals value
    """
    eq: ID
    """
    Does not equal value
    """
    ne: ID
    """
    Is greater than value
    """
    gt: ID
    """
    Is lesser than value
    """
    lt: ID
    """
    Is greater than or equals value
    """
    ge: ID
    """
    Is lesser than or equals value
    """
    le: ID
    """
    Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
    """
    like: ID
    """
    Value not matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
    """
    notLike: ID
}
input IDListExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Is in list of values
    """
    in: ID
    """
    Is not in list of values
    """
    notIn: ID
}
input IntExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Equals value
    """
    eq: Int
    """
    Does not equal value
    """
    ne: Int
    """
    Is greater than value
    """
    gt: Int
    """
    Is lesser than value
    """
    lt: Int
    """
    Is greater than or equals value
    """
    ge: Int
    """
    Is lesser than or equals value
    """
    le: Int
    """
    Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
    """
    like: Int
    """
    Value not matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
    """
    notLike: Int
}
input IntListExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Is in list of values
    """
    in: Int
    """
    Is not in list of values
    """
    notIn: Int
}
type Query {
    areaList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:AreaSortInput,where:AreaWhereInput): [Area]
    userList(id:ID,distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:UserSortInput,where:UserWhereInput): [User]
}
input StringExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Equals value
    """
    eq: String
    """
    Does not equal value
    """
    ne: String
    """
    Is greater than value
    """
    gt: String
    """
    Is lesser than value
    """
    lt: String
    """
    Is greater than or equals value
    """
    ge: String
    """
    Is lesser than or equals value
    """
    le: String
    """
    Value matching (case-insensitive) pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values having 'r' in second position
    """
    like: String
    """
    Value not matching pattern where '%' represents zero or more characters and '_' represents a single character. Eg. '_r%' finds values not having 'r' in second position
    """
    notLike: String
}
input StringListExpression {
    """
    Is value null (true) or not null (false)
    """
    isNull: Boolean
    """
    Is in list of values
    """
    in: String
    """
    Is not in list of values
    """
    notIn: String
}
type User {
    id: ID
    areaId: Int
    area(distinct:[String],limit:Int,offset:Int,first:Int,last:Int,after:Cursor,before:Cursor,sort:AreaSortInput,where:AreaWhereInput): Area
}
input UserSortInput {
    id: SortDirection
    areaId: SortDirection
}
input UserWhereInput {
    and: UserWhereInput
    not: UserWhereInput
    or: UserWhereInput
    id: IDExpression
    areaId: IntExpression
}