scalar DateTime @specifiedBy(url: "https://www.baidu.com")

"""
方向枚举类
"""
enum Direction {
    NORTH@deprecated(reason: "过期了")
    EAST
    SOUTH
    WEST
}

interface Character {
    id: ID!
    name: String!
}

type User implements Character {
    id:ID!
    name:String!
    home:Direction
    birthday:DateTime
}

type Query{
    users(username:[String!]):[User]!
}