scalar Cursor @specifiedBy(url: "https://www.baidu.com")
scalar DateTime @specifiedBy(url: "https://www.baidu.com")

enum Direction {
    ASC
    DESC
}

type User  {
    id:ID!
    username:String!
    nickname:String!
    teams:[Team]!
}

input UserSortInput{
    id:Direction
}

input UserWhereInput{
    not:UserWhereInput
    and:UserWhereInput
    or:UserWhereInput
}

type Team  {
    id:ID!
    name:String!
    users:[User]!
}

type Query{
    users(id:ID,limit:Int,offset:Int,distinct:[String],first:Int,last:Int,after:Cursor,before:Cursor,sort:UserSortInput,where:UserWhereInput):[User]!
}